ValidatorAddress = "0CC835E75E6E3DD60195F2AF69B4AA9BEFFA6D2B"

[Tendermint]
  Seeds = ""
  ListenAddress = "tcp://0.0.0.0:46656"
  Moniker = ""
  TendermintRoot = ".burrow"

[Keys]
  URL = "http://localhost:4767"

[RPC]
  [RPC.V0]
    [RPC.V0.Server]
      ChainId = ""
      [RPC.V0.Server.bind]
        address = ""
        port = 1337
      [RPC.V0.Server.TLS]
        tls = false
        cert_path = ""
        key_path = ""
      [RPC.V0.Server.CORS]
        enable = false
        allow_credentials = false
        max_age = 0
      [RPC.V0.Server.HTTP]
        json_rpc_endpoint = "/rpc"
      [RPC.V0.Server.web_socket]
        websocket_endpoint = "/socketrpc"
        max_websocket_sessions = 50
        read_buffer_size = 4096
        write_buffer_size = 4096
  [RPC.TM]
    ListenAddress = ":46657"

[Logging]
  [Logging.RootSink]
    [Logging.RootSink.Output]
      OutputType = "stderr"
